name: CI

on:
  push:
      paths-ignore:
        - '.*'
        - 'scripts/**'
        - 'README.md'
  pull_request:
      paths-ignore:
        - '.*'
        - 'scripts/**'
        - 'README.md'

env:
  # Customize the CMake build type here (Release, Debug, RelWithDebInfo, etc.)
  BUILD_TYPE: Debug

jobs:
  build-and-tests:

    name: ${{matrix.toolchain}}
    runs-on: ${{matrix.os}}

    strategy:
      matrix:
        toolchain:
          - linux-gcc
          - windows-msvc
          - macos-clang

        configuration:
          - {{env.BUILD_TYPE}}

        include:
          - toolchain: linux-gcc
            os: ubuntu-latest
            compiler: gcc

          - toolchain: windows-msvc
            os: windows-latest
            compiler: msvc

          - toolchain: macos-clang
            os: macos-latest
            compiler: clang

    steps:
    - uses: actions/checkout@v3

    - name: Configure CMake (${{matrix.configuration}})
      run: cmake -B ${{github.workspace}}/build -DCMAKE_BUILD_TYPE=${{matrix.configuration}}

    - name: Build with ${{matrix.compiler}}
      run: cmake --build ${{github.workspace}}/build --config ${{matrix.configuration}}

    - name: Tests
      working-directory: ${{github.workspace}}/build
      env:
        CTEST_OUTPUT_ON_FAILURE: 1
      # Execute tests defined by the CMake configuration.
      # See https://cmake.org/cmake/help/latest/manual/ctest.1.html for more detail
      run: ctest -C ${{matrix.configuration}}

