name: CI linux

defaults:
  run:
    shell: sh

on:
  workflow_dispatch:
  push:
      paths-ignore:
        - '.*'
        - 'scripts/**'
        - 'README.md'
  pull_request:
      paths-ignore:
        - '.*'
        - 'scripts/**'
        - 'README.md'

# Customize the CMake build type here (Release, Debug, RelWithDebInfo, etc.)
env:
  BUILD_TYPE: Debug

jobs:
  build-and-tests:
    runs-on: ubuntu-latest
    continue-on-error: false

    strategy:
      fail-fast: true
      matrix:
        toolchain:
          - clang
          - gcc

        # NOTE: hardcoded -> env.BUILD_TYPE variable cannot be used here! => Sucks!
        include:
          - toolchain: clang
            cc  : clang
            cxx : clang++
            bdir: build/lnx-Debug-clang

          - toolchain: gcc
            cc  : gcc
            cxx : g++
            bdir: build/lnx-Debug-gcc

    name: ${{matrix.toolchain}}

    # TODO: cache deps
    steps:
      # will not work without checkout.
      - uses: actions/checkout@v3

      - name: ENV List All
        run : env

      - name: CMake Configure
        run : >
          cmake -S . -B ${{matrix.bdir}} -D CMAKE_BUILD_TYPE=${{env.BUILD_TYPE}}
          -D CMAKE_C_COMPILER=${{matrix.cc}} -D CMAKE_CXX_COMPILER=${{matrix.cxx}}

      - name: Build
        run : cmake --build ${{matrix.bdir}} --config ${{env.BUILD_TYPE}} -j $(getconf _NPROCESSORS_ONLN)

      - name: Tests
        run : ctest --test-dir ${{matrix.bdir}} -C ${{env.BUILD_TYPE}}

      - name: Runner info lines
        run : |
          ls -la "${{matrix.bdir}}/_deps"

