name: CI Linux

defaults:
  run:
    shell: sh

on:
  push:
      paths-ignore:
        - '.*'
        - 'scripts/**'
        - 'README.md'
  pull_request:
      paths-ignore:
        - '.*'
        - 'scripts/**'
        - 'README.md'

# Customize the CMake build type here (Release, Debug, RelWithDebInfo, etc.)
env:
  BUILD_TYPE: Debug
  BBDIR: ${{github.workspace}}/build

jobs:
  build-and-tests:
    runs-on: ubuntu-latest
    continue-on-error: false

    strategy:
      fail-fast: true
      matrix:
        toolchain:
          - clang
          - gcc

        include:
          - toolchain: clang
            cc : clang
            cxx: clang++

          - toolchain: gcc
            cc : gcc
            cxx: g++

    name: ${{matrix.toolchain}}

    # TODO: cache deps
    steps:
      - name: ENV All
        run : env

      - uses: actions/checkout@v3

      - name: CMake Configure
        run : >
          cmake -S . -B ${{env.BBDIR}} -D CMAKE_BUILD_TYPE=${{env.BUILD_TYPE}}
          -D CMAKE_C_COMPILER=${{matrix.cc}} -D CMAKE_CXX_COMPILER=${{matrix.cxx}}

      - name: Build
        run : cmake --build ${{env.BBDIR}} --config ${{env.BUILD_TYPE}} -j$(nproc)

      - name: Tests
        run : ctest --test-dir ${{env.BBDIR}} -C ${{env.BUILD_TYPE}}

      - name: Runner info lines
        run : |
          ls -la "${{env.BBDIR}}/_deps"

