name: CI Linux

on:
  push:
      paths-ignore:
        - '.*'
        - 'scripts/**'
        - 'README.md'
  pull_request:
      paths-ignore:
        - '.*'
        - 'scripts/**'
        - 'README.md'

env:
  # Customize the CMake build type here (Release, Debug, RelWithDebInfo, etc.)
  BUILD_TYPE: Debug
  CMAKE_BUILD_TYPE:  {{BUILD_TYPE}}
  CMAKE_CONFIG_TYPE: {{BUILD_TYPE}}
  CTEST_OUTPUT_ON_FAILURE: 1

jobs:
  build-and-tests:
    runs-on: ubuntu-latest
    continue-on-error: false

    strategy:
      fail-fast: true
      # TODO: set env variable to actually use compiler
      matrix:
        compiler:
          - gcc
            env:
              CC: /usr/bin/gcc
              CXX: /usr/bin/g++
          - clang
            env:
              CC: /usr/bin/clang
              CXX: /usr/bin/clang++

        # include:
        #   - compiler: gcc
        #     env:
        #       CC:  /usr/bin/gcc
        #       CXX: /usr/bin/g++
        #   - compiler: clang
        #     env:
        #       CC:  /usr/bin/clang
        #       CXX: /usr/bin/clang++

    name: ${{matrix.compiler}}

    # TODO: cache deps
    steps:
    - uses: actions/checkout@v3

    - name: CMake Configure
      # run: cmake -B ${{github.workspace}}/build -DCMAKE_BUILD_TYPE=${{env.BUILD_TYPE}}
      run: cmake -B ${{github.workspace}}/build

    - name: Build
      # run: cmake --build ${{github.workspace}}/build --config ${{env.BUILD_TYPE}}
      run: cmake --build ${{github.workspace}}/build

    - name: Tests
      working-directory: ${{github.workspace}}/build
      # env:
      #   CTEST_OUTPUT_ON_FAILURE: 1
      # run: ctest -C ${{env.BUILD_TYPE}}
      run: ctest
