name: macos (AppleClang)

defaults:
  run:
    shell: sh

# workflow will run after & only if CI:(linux & windows) is successfully passed.
# workflow_dispatch - to be able to run manually even when parent workflow is disabled.
on:
  workflow_dispatch:
  workflow_run:
    workflows: [windows (MSVC)]
    types    : [completed]

jobs:
  build-and-tests:
    # call reusable workflow
    uses: ./.github/workflows/rsbl_build_ci.yml
    with:
      RUNNER    : macos-latest
      TOOLCHAIN_DISPLAY_NAME: AppleClang
      BUILD_TYPE: Debug
      BUILD_DIR : build/mac-Debug-clanga

