name: windows (MSVC)

defaults:
  run:
    shell: sh

# workflow will run after & only if linux CI is successfully passed.
# workflow_dispatch - to be able to run manually even when parent workflow is disabled.
on:
  workflow_dispatch:
  workflow_run:
    workflows: [CI linux]
    types    : [completed]

env:
  RUNNER    : windows-latest
  TDNAME    : MSVC
  BUILD_TYPE: Debug
  BUILD_DIR : build/win-Debug-msvc

jobs:
  build-and-tests:
    # call reusable workflow
    uses: ./.github/workflows/rsbl_build_ci.yml
    with:
      RUNNER    : ${{env.RUNNER}}
      TOOLCHAIN_DISPLAY_NAME: ${{env.TDNAME}}
      BUILD_TYPE: ${{env.BUILD_TYPE}}
      BUILD_DIR : ${{env.BUILD_DIR}}

