name: windows (msvc)

defaults:
  run:
    shell: sh

# workflow will run after & only if linux CI is successfully passed.
# workflow_dispatch - to be able to run manually even when parent workflow is disabled.
on:
  workflow_run:
    workflows: [CI linux]
    types: [completed]
  workflow_dispatch:

env:
  BUILD_TYPE: Debug
  BBDIR: build/windows-msvc

jobs:
  build-and-tests:
    runs-on: windows-latest
    continue-on-error: true # XXX

    if: |
      github.event.workflow_run.conclusion == 'success' ||
      github.event_name == 'workflow_dispatch'

    name: msvc

    steps:
      - name: ENV All
        run : env

      - uses: actions/checkout@v3

      - name: CMake Configure
        run : cmake -S . -B ${{env.BBDIR}} -D CMAKE_BUILD_TYPE=${{env.BUILD_TYPE}}

      - name: Build
        run : cmake --build ${{env.BBDIR}} --config ${{env.BUILD_TYPE}} -j $(nproc)

      - name: Terse Tests with output-on-failure
        run : ctest --test-dir ${{env.BBDIR}} -C ${{env.BUILD_TYPE}} --progress --output-on-failure

      - name: Tests with output-on-failure
        run : ctest --test-dir ${{env.BBDIR}} -C ${{env.BUILD_TYPE}} --output-on-failure

      - name: Terse Tests with verbose Fail Log (re-run the failed cases verbosely)
        run : >
          ctest --test-dir ${{env.BBDIR}} -C ${{env.BUILD_TYPE}} --progress ||
          ctest --test-dir ${{env.BBDIR}} -C ${{env.BUILD_TYPE}} --rerun-failed --output-on-failure

      - name: cat LastTest.log
        run : cat "D:/a/algorithms/algorithms/build/windows-msvc/Testing/Temporary/LastTest.log"

