name: windows (MSVC)

defaults:
  run:
    shell: sh

# workflow will run after & only if linux CI is successfully passed.
# XXX: impossible without hacks to check (workflow_run status == succes) (only status completed)
# workflow_dispatch - to be able to run manually even when parent workflow is disabled.
on:
  workflow_dispatch:
  workflow_run:
    workflows: [CI linux]
    types    : [completed]

# XXX: unfortunately this will not work! -> that's why all hardcoded.
# env:
#   RUNNER    : windows-latest
#   TDNAME    : MSVC
#   BUILD_TYPE: Debug
#   BUILD_DIR : build/win-Debug-msvc

jobs:
  build-and-tests:
    # HACK: to run the job if previous workflow completed with status == success.
    if: |
      github.event_name == 'workflow_dispatch' ||
      github.event.workflow_run.conclusion == 'success'
    # ^ => skip job otherwise.

    # call reusable workflow
    uses: ./.github/workflows/rsbl_build_ci.yml
    with:
      RUNNER    : windows-latest
      TOOLCHAIN_DISPLAY_NAME: MSVC
      BUILD_TYPE: Debug
      BUILD_DIR : build/win-Debug-msvc

